# Site settings
name: And9的笔记
email: andyandwei@163.com
author: And9 WEI
url: 
resume_site: 
github: https://github.com/ANDYsGUITAR
baseurl: 
description: 机器学习，深度学习，笔记分享
meta_description: 
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: ANDYsGUITAR

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

